server:
  port: ${APP_PORT:9999}

worker:
  id: ${WORKER_ID:1}

spring:
  application:
    name: rinhabackend-${WORKER_ID:1}
  main:
    banner-mode: off
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      ssl:
        enable: false

apis:
  payment-processor:
    default:
      url: ${PROCESSOR_DEFAULT_URL:http://localhost:8001}
      timeout: ${TIMEOUT_PAYMENT_PROCESSOR:5000}
    fallback:
      url: ${PROCESSOR_FALLBACK_URL:http://localhost:8002}
      timeout: ${TIMEOUT_PAYMENT_PROCESSOR:5000}

logging:
  level:
    root: ${LOG_LEVEL:INFO}