server:
  port: 8999

spring:
  application:
    name: rinhabackend
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USER_DB:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/rinha
    hikari:
      maximum-pool-size: ${DB_INITIAL_POOL_SIZE:15}
      minimum-idle: ${DB_INITIAL_POOL_SIZE:15}
      idle-timeout: 8000
      connection-timeout: 5000
      max-lifetime: 10000
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      jakarta.persistence.query.timeout: 8000
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    root: ${LOG_LEVEL:INFO}