x-service-templates:
  api1: &api-processor
    image: jjeanjacques10/payment-processor
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

services:
  api1:
    <<: *api-processor
    container_name: api1
    hostname: api1
    ports:
      - 9999:8080
    environment:
      - APP_PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  redis:
    image: redis:7.2-alpine
    container_name: rinha
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true